#!/usr/bin/env bash
# Fetches and builds the pinned ns-3 + 5G-LENA (nr) toolchain used by ns3_sim/.
#
# The vendored ns-3-dev + contrib/nr source trees are NOT committed to this repository
# (see .gitignore) — they are an external simulator dependency, fetched here at pinned
# tags, analogous to installing a compiler. Only our own scenario source under ns3_sim/
# is project-authored and tracked in git. See ns3_sim/README.md for the full rationale,
# the exact prerequisite packages, and troubleshooting notes (prompt.md §0.2-0.4).
set -euo pipefail

NS3_TAG="ns-3.48"
NR_TAG="v5.1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
NS3_SIM_DIR="${REPO_ROOT}/ns3_sim"
NS3_DEV_DIR="${NS3_SIM_DIR}/ns-3-dev"

echo "== Checking required compiler/build tools =="
for tool in g++ cmake ninja git python3; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "MISSING REQUIRED TOOL: $tool" >&2
    exit 1
  fi
done
g++ --version | head -1
cmake --version | head -1
python3 --version

echo "== Checking nr module prerequisites (sudo-installed system packages) =="
missing=()
for pkg in libzmq3-dev cppzmq-dev; do
  dpkg -s "$pkg" >/dev/null 2>&1 || missing+=("$pkg")
done
if [ "${#missing[@]}" -gt 0 ]; then
  echo "WARNING: missing packages required for the ZeroMQ telemetry producer: ${missing[*]}"
  echo "  Install with: sudo apt-get update && sudo apt-get install -y ${missing[*]}"
  echo "  Continuing — ns-3 core + nr module will still build, but zmq_telemetry_exporter"
  echo "  will not link until these are installed."
fi
for pkg in libeigen3-dev sqlite3 libsqlite3-dev; do
  dpkg -s "$pkg" >/dev/null 2>&1 || echo "NOTE: optional nr package not installed: $pkg (disables MIMO / some example programs only)"
done

echo "== Fetching ns-3-dev @ ${NS3_TAG} =="
if [ -d "${NS3_DEV_DIR}/.git" ]; then
  echo "ns-3-dev already present at ${NS3_DEV_DIR}, skipping clone."
else
  git clone --branch "${NS3_TAG}" --depth 1 https://gitlab.com/nsnam/ns-3-dev.git "${NS3_DEV_DIR}"
fi

echo "== Fetching nr (5G-LENA) @ ${NR_TAG} =="
if [ -d "${NS3_DEV_DIR}/contrib/nr/.git" ]; then
  echo "contrib/nr already present, skipping clone."
else
  git clone --branch "${NR_TAG}" --depth 1 https://gitlab.com/cttc-lena/nr.git "${NS3_DEV_DIR}/contrib/nr"
fi

echo "== Wiring our scenario into the scratch/ build (Module 1's nr_5g_telemetry_sim.cc) =="
SCRATCH_TARGET_DIR="${NS3_DEV_DIR}/scratch/nr_5g_telemetry_sim"
mkdir -p "${SCRATCH_TARGET_DIR}"
ln -sf "../../../nr_5g_telemetry_sim.cc" "${SCRATCH_TARGET_DIR}/nr_5g_telemetry_sim.cc"
cat > "${SCRATCH_TARGET_DIR}/CMakeLists.txt" <<'EOF'
# Builds nr_5g_telemetry_sim (Module 1's real NS-3/5G-LENA telemetry producer) linked against
# libzmq, in addition to the standard ns-3 + nr libraries every other scratch program gets.
# The source file itself is a symlink to the project-authored, git-tracked copy at
# ns3_sim/nr_5g_telemetry_sim.cc (see ns3_sim/README.md) — this subdirectory and its
# CMakeLists.txt are regenerated by scripts/setup_ns3.sh and are not tracked in git, since
# everything under ns3_sim/ns-3-dev is a vendored external build dependency.
build_exec(
  EXECNAME nr_5g_telemetry_sim
  EXECNAME_PREFIX scratch_
  SOURCE_FILES "${CMAKE_CURRENT_SOURCE_DIR}/nr_5g_telemetry_sim.cc"
  LIBRARIES_TO_LINK "${ns3-libs}" "${ns3-contrib-libs}" zmq
  EXECUTABLE_DIRECTORY_PATH ${CMAKE_OUTPUT_DIRECTORY}/scratch/nr_5g_telemetry_sim/
)
EOF

echo "== Configuring (release, examples+tests on) =="
cd "${NS3_DEV_DIR}"
./ns3 configure --build-profile=release --enable-examples --enable-tests -- -DCMAKE_BUILD_TYPE=Release

echo "== Building (this can take a while; pass NS3_BUILD_JOBS to override the default) =="
./ns3 build -j "${NS3_BUILD_JOBS:-3}"

echo "== Done. Run './ns3 run <program>' from ${NS3_DEV_DIR}, or see ns3_sim/README.md =="
